#!/bin/sh
docker run -v "$(pwd):/src/" -v "${PWD}/.sqitch:/root/.sqitch/" \
  -e "SQITCH_PASSWORD=${SQITCH_PASSWORD}" \
  --network hverdagsverktoy-network \
  --rm docteurklein/sqitch:pgsql \
  -d hverdagsverktoy -u root -h "${SQITCH_HOST}" "$@"
