-- Deploy floq:add_employee_user to pg

BEGIN;

CREATE USER employee ENCRYPTED PASSWORD :'employee-password';
GRANT ALL PRIVILEGES ON SCHEMA public TO employee;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to employee;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to employee;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to employee;
GRANT ALL PRIVILEGES ON DATABASE floq TO employee;

COMMIT;
