-- Revert floq:add_employee_user from pg

BEGIN;

REVOKE ALL PRIVILEGES ON SCHEMA public FROM employee;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM employee;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM employee;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM employee;
REVOKE ALL PRIVILEGES ON DATABASE floq FROM employee;
DROP USER IF EXISTS employee;

COMMIT;
